# Generated by Django 6.0.1 on 2026-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("created_date",)},
        ),
    ]
