# Generated by Django 6.0.1 on 2026-02-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0002_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_date",)},
        ),
    ]
