# Generated by Django 6.0.1 on 2026-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0003_alter_contact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
