# Generated by Django 6.0.1 on 2026-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("First_App", "0004_newsletter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
