# Generated by Django 6.0.1 on 2026-02-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="Blog.category"),
        ),
    ]
