# Generated by Django 6.0.1 on 2026-02-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0008_comment_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="approach",
            new_name="approved",
        ),
    ]
