# Generated by Django 6.0.1 on 2026-02-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_rename_approach_comment_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
    ]
