# Generated by Django 6.0.1 on 2026-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="loginrequired",
            field=models.BooleanField(default=False),
        ),
    ]
